---
version: '2'
services:
  confluent:
    image: 'ksql-clickstream-plane:latest'
    build:
      context: docker/
    hostname: confluent
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
      - "8088:8088"
    command: "/bin/sh -c /scripts/run_confluent"
    environment:
      TZ: ${TZ_SET}
    volumes:
      - ./scripts:/scripts
      - ./raspberry-pi:/raspberry-pi
      - zk-data:/var/lib/zookeeper/data
      - zk-txn-logs:/var/lib/zookeeper/log
      - kafka-data:/var/lib/kafka/data
    extra_hosts:
      - "moby:127.0.0.1"

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:${ELST_VER}'
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - confluent
    environment:
      TZ: ${TZ_SET}
      discovery.type: 'single-node'
    extra_hosts:
      - "moby:127.0.0.1"

  kibana:
    image: 'docker.elastic.co/kibana/kibana-oss:${ELST_VER}'
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    hostname: kibana
    environment:
      TZ: ${TZ_SET}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    extra_hosts:
      - "moby:127.0.0.1"

volumes:
  zk-data:
    external: true
  zk-txn-logs:
    external: true
  kafka-data:
    external: true
