DROP TABLE IF EXISTS icao_to_aircraft;
drop stream IF EXISTS icao_to_aircraft_rekey DELETE TOPIC;
drop stream IF EXISTS icao_to_aircraft_stream;
DROP TABLE IF EXISTS callsign_details;
drop stream IF EXISTS callsign_details_rekey DELETE TOPIC;
drop stream IF EXISTS callsign_details_stream;
drop table IF EXISTS locationtable DELETE TOPIC;
drop table IF EXISTS callsigntable DELETE TOPIC;
drop stream IF EXISTS location_and_details_stream DELETE TOPIC;
drop stream IF EXISTS ident_callsign_stream DELETE TOPIC;
drop stream IF EXISTS location_stream;
drop stream IF EXISTS ident_stream;
