#!/usr/bin/env bash

unset http_proxy
unset https_proxy
export http_proxy
export https_proxy

HOST=localhost

echo "**********"
echo "Loading Elastic Dynamic Templates"
echo "**********"

curl -XDELETE "http://${HOST}:9200/_template/kafkaconnect/"
echo
echo

cat ../config/es-dynamic-template.json | curl -XPUT "http://${HOST}:9200/_template/kafkaconnect/" -H 'Content-Type: application/json' -d @- > dynamic_template.log

if hash jq 2>/dev/null; then
    cat dynamic_template.log | jq
else
    cat dynamic_template.log
fi
rm dynamic_template.log

echo

