#!/bin/bash

unset http_proxy
unset https_proxy
export http_proxy
export https_proxy

HOST=localhost

topic_to_elastic () {
  config=$1
  echo "**********"
  echo "Uploading connector config $config"
  echo "**********"

  cat "../config/$config" | curl -X "POST" "http://${HOST}:8083/connectors/" \
     -H "Content-Type: application/json" \
     -d @- > connector.log

  if hash jq 2>/dev/null; then
      cat connector.log | jq
  else
      cat connector.log
  fi
  rm connector.log

  echo
}


topic_to_elastic connector-es-loc_det_strm.json
# add more connector configs as needed

